import { ToolCategory } from '@/types/tools';

export const toolCategories: ToolCategory[] = [
  {
    id: 'video',
    name: '视频工具',
    description: '视频编辑、转换和处理工具',
    icon: '🎬',
    tools: [
      {
        id: 'video-converter',
        name: '视频格式转换',
        description: '转换视频格式',
        icon: '🔄',
        path: '/tools/video/converter',
      },
      {
        id: 'video-compressor',
        name: '视频压缩',
        description: '压缩视频文件大小',
        icon: '📦',
        path: '/tools/video/compressor',
      },
    ],
  },
  {
    id: 'audio',
    name: '音频工具',
    description: '音频编辑、转换和处理工具',
    icon: '🎵',
    tools: [
      {
        id: 'audio-converter',
        name: '音频格式转换',
        description: '转换音频格式',
        icon: '🔄',
        path: '/tools/audio/converter',
      },
      {
        id: 'audio-cutter',
        name: '音频剪辑',
        description: '剪辑音频文件',
        icon: '✂️',
        path: '/tools/audio/cutter',
      },
    ],
  },
  {
    id: 'image',
    name: '图片工具',
    description: '图片编辑、转换和处理工具',
    icon: '🖼️',
    tools: [
      {
        id: 'image-converter',
        name: '图片格式转换',
        description: '转换图片格式',
        icon: '🔄',
        path: '/tools/image/converter',
      },
      {
        id: 'image-compressor',
        name: '图片压缩',
        description: '压缩图片文件大小',
        icon: '📦',
        path: '/tools/image/compressor',
      },
      {
        id: 'image-cropper',
        name: '图片裁剪',
        description: '证件照尺寸裁剪',
        icon: '✂️',
        path: '/tools/image/cropper',
      },
      {
        id: 'image-resizer',
        name: '图片调整大小',
        description: '调整图片尺寸',
        icon: '📏',
        path: '/tools/image/resizer',
      },
      {
        id: 'image-watermark',
        name: '图片水印',
        description: '添加文字水印',
        icon: '🖋️',
        path: '/tools/image/watermark',
      },
    ],
  },
  {
    id: 'document-processing',
    name: '文档处理',
    description: '文档编辑和处理工具',
    icon: '📄',
    tools: [
      {
        id: 'pdf-merger',
        name: 'PDF合并',
        description: '合并多个PDF文件',
        icon: '📑',
        path: '/tools/document/pdf-merger',
      },
      {
        id: 'pdf-splitter',
        name: 'PDF拆分',
        description: '拆分PDF文件',
        icon: '✂️',
        path: '/tools/document/pdf-splitter',
      },
    ],
  },
  {
    id: 'document-conversion',
    name: '文档转换',
    description: '文档格式转换工具',
    icon: '📝',
    tools: [
      {
        id: 'doc-to-pdf',
        name: 'Word转PDF',
        description: '将Word文档转换为PDF',
        icon: '📄',
        path: '/tools/conversion/doc-to-pdf',
      },
      {
        id: 'pdf-to-word',
        name: 'PDF转Word',
        description: '将PDF转换为Word文档',
        icon: '📝',
        path: '/tools/conversion/pdf-to-word',
      },
    ],
  },
  {
    id: 'developer-tools',
    name: '开发工具',
    description: '开发者常用工具集合',
    icon: '💻',
    tools: [
      {
        id: 'color-picker',
        name: '颜色选择器',
        description: '在线颜色选择和预览',
        icon: '🎨',
        path: '/tools/developer/color-picker',
      },
      {
        id: 'color-converter',
        name: '颜色转换',
        description: 'HEX/RGB/HSL颜色格式转换',
        icon: '🌈',
        path: '/tools/developer/color-converter',
      },
      {
        id: 'json-formatter',
        name: 'JSON格式化',
        description: 'JSON格式化和验证',
        icon: '📋',
        path: '/tools/developer/json-formatter',
      },
      {
        id: 'regex-tester',
        name: '正则测试',
        description: '正则表达式在线测试',
        icon: '🔍',
        path: '/tools/developer/regex-tester',
      },
      {
        id: 'url-encoder',
        name: 'URL编码',
        description: 'URL编码和解码工具',
        icon: '🔗',
        path: '/tools/developer/url-encoder',
      },
    ],
  },
  {
    id: 'life-tools',
    name: '生活工具',
    description: '日常生活实用工具',
    icon: '🏠',
    tools: [
      {
        id: 'mortgage-calculator',
        name: '房贷计算器',
        description: '房贷月供和利息计算',
        icon: '🏡',
        path: '/tools/life/mortgage-calculator',
      },
      {
        id: 'date-calculator',
        name: '日期计算',
        description: '日期间隔和天数计算',
        icon: '📅',
        path: '/tools/life/date-calculator',
      },
      {
        id: 'time-calculator',
        name: '时间计算',
        description: '时间间隔和时差计算',
        icon: '⏰',
        path: '/tools/life/time-calculator',
      },
      {
        id: 'bmi-calculator',
        name: 'BMI计算器',
        description: '身体质量指数计算',
        icon: '⚖️',
        path: '/tools/life/bmi-calculator',
      },
    ],
  },
  {
    id: 'office-assistant',
    name: '办公辅助',
    description: '办公自动化辅助工具',
    icon: '💼',
    tools: [
      {
        id: 'qr-code-generator',
        name: '二维码生成',
        description: '生成二维码',
        icon: '📱',
        path: '/tools/office/qr-generator',
      },
      {
        id: 'barcode-generator',
        name: '条形码生成',
        description: '生成条形码',
        icon: '📊',
        path: '/tools/office/barcode-generator',
      },
    ],
  },
  {
    id: 'text',
    name: '文本工具',
    description: '文本处理和转换工具',
    icon: '📃',
    tools: [
      {
        id: 'text-formatter',
        name: '文本格式化',
        description: '格式化文本内容',
        icon: '✏️',
        path: '/tools/text/formatter',
      },
      {
        id: 'text-diff',
        name: '文本对比',
        description: '对比两段文本差异',
        icon: '🔍',
        path: '/tools/text/diff',
      },
      {
        id: 'text-counter',
        name: '字数统计',
        description: '统计文本字数',
        icon: '🔢',
        path: '/tools/text/counter',
      },
    ],
  },
  {
    id: 'number',
    name: '数字工具',
    description: '数字计算和转换工具',
    icon: '🔢',
    tools: [
      {
        id: 'calculator',
        name: '计算器',
        description: '基础计算器',
        icon: '🧮',
        path: '/tools/number/calculator',
      },
      {
        id: 'number-converter',
        name: '进制转换',
        description: '数字进制转换',
        icon: '🔄',
        path: '/tools/number/converter',
      },
    ],
  },
  {
    id: 'encryption',
    name: '加密工具',
    description: '加密解密和哈希工具',
    icon: '🔐',
    tools: [
      {
        id: 'aes-encrypt',
        name: 'AES加密',
        description: 'AES-GCM 长文本加解密',
        icon: '🛡️',
        path: '/tools/encryption/aes',
      },
      {
        id: 'hash-generator',
        name: '哈希生成',
        description: '生成MD5/SHA哈希',
        icon: '🔑',
        path: '/tools/encryption/hash',
      },
      {
        id: 'base64-encoder',
        name: 'Base64编码',
        description: 'Base64编码解码',
        icon: '🔤',
        path: '/tools/encryption/base64',
      },
    ],
  },
  {
    id: 'unit-conversion',
    name: '单位转换',
    description: '各种单位转换工具',
    icon: '⚖️',
    tools: [
      {
        id: 'length-converter',
        name: '长度转换',
        description: '长度单位转换',
        icon: '📏',
        path: '/tools/unit/length',
      },
      {
        id: 'weight-converter',
        name: '重量转换',
        description: '重量单位转换',
        icon: '⚖️',
        path: '/tools/unit/weight',
      },
      {
        id: 'temperature-converter',
        name: '温度转换',
        description: '温度单位转换',
        icon: '🌡️',
        path: '/tools/unit/temperature',
      },
    ],
  },
];
